### ISSUE TITLE
Fix build errors

### ISSUE THREAD

**Issue by ozgurozbek** [nutrition-ist/fit-nutrition-front#41]
Error: src/App.tsx(2,1): error TS6133: 'Home' is declared but its value is never read.
Error: src/components/ToggleColorMode.tsx(1,1): error TS6133: 'React' is declared but its value is never read.
Error: src/pages/PatientProfile.tsx(8,28): error TS6133: 'event' is declared but its value is never read.
Error: src/pages/Register.tsx(4[9](https://github.com/nutrition-ist/fit-nutrition-front/actions/runs/12207867426/job/34060050527#step:5:10),13): error TS6133: 'response' is declared but its value is never read.
Error: src/themes/getSignInTheme.tsx(1,1): error TS6133: 'React' is declared but its value is never read.
Error: Process completed with exit code 2.

**Comment by ozgurozbek** [comment]
> figappversiontwo.client@0.0.0 build
> tsc && vite build

There was an error exporting the HTTPS developer certificate to a file. Please create the target directory before exporting. Choose permissions carefully when creating it.
failed to load config from /home/runner/work/fit-nutrition-front/fit-nutrition-front/vite.config.ts
error during build:
Error: Could not create certificate.
    at file:///home/runner/work/fit-nutrition-front/fit-nutrition-front/vite.config.ts.timestamp-1733757541455-ba8e82079fe04.mjs:24:11
    at ModuleJob.run (node:internal/modules/esm/module_job:2[6](https://github.com/nutrition-ist/fit-nutrition-front/actions/runs/12238642708/job/34137210345#step:5:7)8:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:543:26)
    at async loadConfigFromBundledFile (file:///home/runner/work/fit-nutrition-front/fit-nutrition-front/node_modules/vite/dist/node/chunks/dep-CB_[7](https://github.com/nutrition-ist/fit-nutrition-front/actions/runs/12238642708/job/34137210345#step:5:8)IfJ-.js:66691:15)
    at async loadConfigFromFile (file:///home/runner/work/fit-nutrition-front/fit-nutrition-front/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:66532:24)
    at async resolveConfig (file:///home/runner/work/fit-nutrition-front/fit-nutrition-front/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:66140:24)
    at async build (file:///home/runner/work/fit-nutrition-front/fit-nutrition-front/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:65237:1[8](https://github.com/nutrition-ist/fit-nutrition-front/actions/runs/12238642708/job/34137210345#step:5:9))
    at async CAC.<anonymous> (file:///home/runner/work/fit-nutrition-front/fit-nutrition-front/node_modules/vite/dist/node/cli.js:828:5)
Error: Process completed with exit code 1.
